# 官公式 httpd イメージでは dav 系がコメントアウトされているため明示ロード
LoadModule dav_module          modules/mod_dav.so
LoadModule dav_svn_module      modules/mod_dav_svn.so
LoadModule authz_svn_module    modules/mod_authz_svn.so

<Location /svn>
    DAV svn
    SVNParentPath /var/svn

    AuthType Basic
    AuthName "Subversion Repository"
    AuthUserFile /var/svn/.htpasswd
    Require valid-user
</Location>
